import Header from "@/components/Header";
import "./globals.scss";
import Footer from "@/components/Footer";
import { VinotecaProvider } from "@/context/VinotecaContext";

export const metadata = {
  title: "Vinoteca Alvarez Rapetti",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <VinotecaProvider>
          <Header />
          <main className="heroSize">
            {children}
          </main>
          <Footer />
        </VinotecaProvider>
      </body>
    </html>
  );
}
